import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "test2",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children:React.ReactNode}>) {
  // console.log("indata = ", inData);
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <b>layout starts here</b>
        {children}
      </body>
    </html>
  );
}
