import type { Metadata } from "next";
import { Noto_Sans_Display, Noto_Sans_Mono } from "next/font/google";
import "./globals.css";

const NotoSansDisplay = Noto_Sans_Display({
  variable: "--font-notosans",
  subsets: ["latin"],
});

const NotoSansMono = Noto_Sans_Mono({
  variable: "--font-notomono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "test2",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children:React.ReactNode}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className="p-3">
        {children}
      </body>
    </html>
  );
}
